import 'bootstrap/js/dist/modal'
import 'bootstrap/js/dist/collapse'
import 'bootstrap/js/dist/tab'
import './global/common'
import './global/loading'
import './global/output-message'
import './global/emoji'
import './global/chat-utils'
import './messenger/profile'
import './messenger/setting'
import './messenger/common-chat'
import './messenger/messenger'
import './messenger/member'
import './messenger/search'

console.log('page sub messenger');